# Makefile for the UZH beamer presentation template
# Builds every top-level *.tex document to PDF with latexmk + pdflatex.
# latexmk resolves reruns and calls bibtex for ref.bib automatically.

# --- Using the theme from another directory ----------------------------------
# A talk or poster does not need a copy of the theme. Create a directory with
# just your .tex (and optionally your own ref.bib) and a two-line Makefile
# pointing at the folder for your document kind:
#
#     TEMPLATE := ../../template/latex/slides      # beamer talks
#     TEMPLATE := ../../template/latex/poster      # article-class posters
#     include $(TEMPLATE)/Makefile
#
# `make` there builds the PDF next to your .tex, while the .sty files, img/
# and the fallback ref.bib keep living in the template tree. TEXINPUTS /
# BIBINPUTS below is what makes that resolve; nothing is copied and nothing
# is symlinked. slides/Makefile and poster/Makefile are thin wrappers around
# this engine: they set the mode (poster sets BEAMER=0) and include this file.
TEMPLATE ?= .

# kpathsea searches these for \usepackage, \includegraphics and \bibliography.
# Two template directories go on the path: $(TEMPLATE) holds the mode-specific
# .sty files (slides/ or poster/), and the directory of THIS Makefile holds
# the shared assets (img/, uzhsetup.sty) -- so img/uzh-logo.pdf in the outer
# theme and in \posterheader resolves no matter where make was invoked. The
# trailing ':' means "then the normal search path"; the current directory is
# always searched first, so a local ref.bib or img/ still wins over the shared
# one. Absolute, because latexmk runs the engine from its own working
# directory. $(lastword $(MAKEFILE_LIST)) is this file, because the line runs
# before any further include.
TEMPLATEDIR  := $(abspath $(TEMPLATE))
TEMPLATEROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
export TEXINPUTS := $(TEMPLATEDIR):$(TEMPLATEROOT):$(TEXINPUTS)
export BIBINPUTS := $(TEMPLATEDIR):$(TEMPLATEROOT):$(BIBINPUTS)

# The *-draft.tex, *-frames.tex and *_short.tex driver files are generated by
# the targets below, so they must not be picked up as documents in their own
# right.
TEX = $(filter-out %-draft.tex %-frames.tex %_short.tex,$(wildcard *.tex))
PDF = $(patsubst %.tex,%.pdf,$(TEX))

# A PDF is stale whenever the theme, the bibliography or an image changes, not
# only when its own .tex does. Without these prerequisites make reports
# "Nothing to be done" after a .sty edit and the PDF silently stays out of date.
# Both trees are listed so an edit to the shared theme rebuilds every talk that
# uses it; when TEMPLATE is '.' the duplicate wildcards simply collapse.
DEPS = $(sort $(wildcard *.sty) $(wildcard $(TEMPLATE)/*.sty) \
              $(wildcard $(TEMPLATEROOT)/*.sty) \
              $(wildcard *.bib) $(wildcard $(TEMPLATE)/*.bib) \
              $(wildcard img/*) $(wildcard $(TEMPLATEROOT)/img/*))

LATEXMK      = latexmk
PDFLATEX     = pdflatex -interaction=nonstopmode -synctex=1
LATEXMKFLAGS = -pdf -pdflatex="$(PDFLATEX)" -halt-on-error

.PHONY: all pdf draft watch watch-draft clean cleanall
.SUFFIXES: .tex .pdf

# `make` builds the stepped deck AND the collapsed <doc>_short.pdf; use
# `make pdf` or `make short` for one of the two alone.
#
# A directory holding an article-class document -- a poster on uzhposter.sty,
# for example -- sets BEAMER := 0 before the include. `make` then builds only
# the plain PDF, and the beamer-only targets (draft, short, frames,
# watch-draft) explain themselves instead of failing inside pdflatex.
BEAMER ?= 1

all: pdf
ifeq ($(strip $(BEAMER)),1)
all: short
endif

pdf: $(PDF)

# Static pattern rule: each top-level PDF depends on its source and on the
# shared style files. latexmk decides how many pdflatex passes are actually
# needed (and exits in ~0.1s when nothing changed), so re-entering it on every
# make is cheap. Static (limited to $(PDF)) and not a bare `%.pdf: %.tex`
# rule: img/ holds a .tex/.pdf pair too (the UZH_dm3l wordmark, rebuilt by
# hand -- see img/UZH_dm3l.tex), and a bare pattern rule would match that PDF
# through $(DEPS) and rebuild it into the wrong directory.
$(PDF): %.pdf: %.tex $(DEPS)
	$(LATEXMK) $(LATEXMKFLAGS) $<

# --- Fast draft builds -------------------------------------------------------
# The section navigation bar is re-typeset on every slide and accounts for
# roughly two thirds of each pdflatex pass. A draft build suppresses it, cutting
# a one-line rebuild from ~3.7s to ~1.5s. Everything below the header is
# unchanged, so this is for iterating on content; run `make` before presenting.
#
# The generated <doc>-draft.tex is a thin driver with its own .aux files, so
# draft and final builds never invalidate each other.
DRAFT    = $(patsubst %.tex,%-draft.tex,$(TEX))
DRAFTPDF = $(patsubst %.tex,%-draft.pdf,$(TEX))

ifeq ($(strip $(BEAMER)),1)
draft: $(DRAFTPDF)
endif

%-draft.tex: %.tex
	@printf '%%%% Generated by `make draft` -- do not edit, do not commit.\n' > $@
	@printf '\\AtBeginDocument{\\setbeamertemplate{headline}{}}\n' >> $@
	@printf '\\input{$<}\n' >> $@

%-draft.pdf: %-draft.tex %.tex $(DEPS)
	$(LATEXMK) $(LATEXMKFLAGS) $<

.PRECIOUS: %-draft.tex

# --- Short PDF: one page per frame, stepping collapsed -----------------------
# The step reveals (steplist, \stepblockfade, ...) turn one frame into many
# near-identical pages, which is right for the talk and wrong for a version to
# print, mail or read. `make short` builds <doc>_short.pdf through beamer's
# handout mode: each frame collapses to ONE page that shows its final state
# (uzhnavigation.sty renders every step black there). Content, layout and page
# order stay identical to the stepped deck.
#
#     make short        <doc>_short.pdf only     (alias: make shorter)
#     make              <doc>.pdf AND <doc>_short.pdf
#
# The generated <doc>_short.tex is a thin driver with its own .aux files, so
# short and final builds never invalidate each other.
SHORT    = $(patsubst %.tex,%_short.tex,$(TEX))
SHORTPDF = $(patsubst %.tex,%_short.pdf,$(TEX))

.PHONY: short shorter
ifeq ($(strip $(BEAMER)),1)
short: $(SHORTPDF)
shorter: short
endif

%_short.tex: %.tex
	@printf '%%%% Generated by `make short` -- do not edit, do not commit.\n' > $@
	@printf '\\PassOptionsToClass{handout}{beamer}\n' >> $@
	@printf '\\input{$<}\n' >> $@

%_short.pdf: %_short.tex %.tex $(DEPS)
	$(LATEXMK) $(LATEXMKFLAGS) $<

.PRECIOUS: %_short.tex

# --- Single-frame preview ----------------------------------------------------
# beamer's own \includeonlyframes: typeset only the frames you are working on.
# Tag them with a label -- \begin{frame}[label=math]{Mathematics} -- then
#
#     make frames FRAMES=math,tables
#
# ~0.75s regardless of how long the deck is, because unselected frames are
# skipped entirely. The output is those frames only, with the navigation bar
# suppressed and the footer slide numbers therefore meaningless; it is a preview
# of one slide's layout, not the deck. Run `make` for the real thing.
FRAMES ?=

.PHONY: frames
ifeq ($(strip $(BEAMER)),1)
frames:
ifeq ($(strip $(FRAMES)),)
	$(error set FRAMES to one or more frame labels, e.g. make frames FRAMES=math,tables)
endif
	@printf '%%%% Generated by `make frames` -- do not edit, do not commit.\n' > $(FRAMESTEX)
	@printf '\\AtBeginDocument{\\includeonlyframes{$(FRAMES)}\\setbeamertemplate{headline}{}}\n' >> $(FRAMESTEX)
	@printf '\\input{$(firstword $(TEX))}\n' >> $(FRAMESTEX)
	$(LATEXMK) $(LATEXMKFLAGS) $(FRAMESTEX)
endif

FRAMESTEX = $(patsubst %.tex,%-frames.tex,$(firstword $(TEX)))

# Friendly stubs when BEAMER=0: these targets drive beamer overlays and have
# no meaning for an article-class document.
ifneq ($(strip $(BEAMER)),1)
draft short shorter frames watch-draft html:
	@echo "make $@: beamer-only target; this directory sets BEAMER=0 (article-class document)" >&2; exit 1
endif

# --- Accessible HTML export --------------------------------------------------
# Pandoc-based, for screen readers; see slides/latex2html.sh. Not part of
# `all`, and slides-only: the script lives in slides/ and converts talks.
HTML = $(patsubst %.tex,%.html,$(TEX))

.PHONY: html
ifeq ($(strip $(BEAMER)),1)
html: $(HTML)
endif

%.html: %.tex $(DEPS)
	$(TEMPLATE)/latex2html.sh $<

# --- Continuous preview ------------------------------------------------------
# Rebuild on save (Ctrl-C to stop). This is the fastest edit loop: latexmk stays
# resident, watches every dependency it recorded, and rebuilds on each save.
watch:
	$(LATEXMK) $(LATEXMKFLAGS) -pvc $(TEX)

# Same loop, against the draft build.
ifeq ($(strip $(BEAMER)),1)
watch-draft: $(DRAFT)
	$(LATEXMK) $(LATEXMKFLAGS) -pvc $(DRAFT)
endif

# Remove build artifacts but keep the PDFs (<doc>_short.pdf is a deliverable
# like <doc>.pdf, so only its driver .tex goes; latexmk -c above already
# cleaned its .aux family while the driver still existed).
clean:
	$(LATEXMK) -c
	rm -f *~ *.nav *.snm *.vrb *.bbl *.blg *.backup Rplots.pdf
	rm -f $(patsubst %.tex,%-draft.*,$(TEX)) $(patsubst %.tex,%-frames.*,$(TEX))
	rm -f $(SHORT)

# Remove build artifacts and the generated PDFs.
cleanall:
	$(LATEXMK) -C
	rm -f *~ *.nav *.snm *.vrb *.bbl *.blg *.backup Rplots.pdf $(PDF)
	rm -f $(patsubst %.tex,%-draft.*,$(TEX)) $(patsubst %.tex,%-frames.*,$(TEX))
	rm -f $(patsubst %.tex,%_short.*,$(TEX))
