# Beamer slide decks on the UZH theme. Include this file from your talk
# directory with a two-line Makefile:
#
#     TEMPLATE := ../../template/latex/slides
#     include $(TEMPLATE)/Makefile
#
# Running `make` HERE builds the demo deck template.tex. The build engine and
# the shared assets (img/, uzhsetup.sty) live one level up, in ../Makefile.
TEMPLATE ?= .
include $(TEMPLATE)/../Makefile
